### ISSUE TITLE
My controller does not work anymore

### ISSUE THREAD

**Issue by bast496** [loganmc10/m64p#12] opened 2020-03-30 12:16 UTC
Hi,
On the build of 19th March, it seems I have 2 problems:
- in my profile, I cannot assign the C buttons of my controller
- when I select my profile and my controller ("0:HuiJia SNES Controller") then launch a game, my controller does not work. If I go back in the controller configuration, I see the gamepad has switched back to "Auto". 

My controller was working OK on the build of 3rd February using the previous controller plugin.
Please find attached some logs.
[logs.txt](https://github.com/loganmc10/m64p/files/4402552/logs.txt)

Regards,
Bastien

**Comment by loganmc10** [comment] 2020-03-30 12:56
What kind of controller is it? I see "HuiJia SNES Controller", but is that some kind of adapter to a retro controller?

**Comment by bast496** [comment] 2020-03-30 13:55
Yes, this is a "N64 controller adapter for PC USB". It is is plugged in USB to my PC, and I plug on it a classic N64 controller.

**Comment by loganmc10** [comment] 2020-03-30 14:01
Ok one last question, are you using Windows or Linux?

**Comment by bast496** [comment] 2020-03-30 14:04
Linux, Ubuntu 18.04.

**Comment by loganmc10** [comment] 2020-03-30 15:37
Unfortunately I can't reproduce your issue using my controller (I just have a regular Xbox style controller).

It's not surprising to me that the C buttons don't work, the new input plugin basically expects an Xbox style controller to work. You could trying using xboxdrv.

If you go here: https://wiki.archlinux.org/index.php/Gamepad#xboxdrv there is a section called ```Mimic Xbox 360 controller with other controllers``` that goes over how to make a non-standard controller appear like an Xbox style controller

**Comment by loganmc10** [comment] 2020-04-01 20:55
You can try the latest build: https://github.com/loganmc10/m64p/releases

It adds support for these types of controllres, hopefully it'll fix your issue

**Comment by bast496** [comment] 2020-04-04 11:31
Just tried the build from 1st April:
- I can create my profile, all buttons can now be mapped
- after selecting this profile and my controller "0:HuiJia SNES Controller", I launch a game, but same problem, the controller does not work. Going back in the controller configuration, the gamepad has switched back to "Auto", and sometimes my controller is no longer in the drop list.

Tried xboxdrv as well (profile Auto and gamepad "0:X360 Controller"), but exact same problem after launching a game.

**Comment by loganmc10** [comment] 2020-04-10 03:34
Can you try this release: https://github.com/loganmc10/m64p/releases/tag/Apr92020

And let me know? I pushed some controller fixes

**Comment by bast496** [comment] 2020-04-13 14:04
Just tried this build from 9th April, but unfortunately same problem.

**Comment by Jaffacakelover** [comment] 2020-06-11 19:25
I believe I am having the same issue.
I'm using the latest files (M64P June62020-4d7af20) on Windows 10, with an old Mayflash Dual N64 to USB adapter.
It shows up as '0:HuiJia SNES Controller' and '1:HuiJia SNES Controller' in the config, so I wonder if it shares VID/PID.
Funny thing is, the Profile Editor detects the controller fine, and I can set all the buttons, but no inputs work ingame! I've tried 0 and 1 in case I'd plugged my pad into the wrong slot, but no dice.

**Comment by loganmc10** [comment] 2020-06-11 22:26
@Jaffacakelover can you post a screenshot of what the profile looks like?

**Comment by Jaffacakelover** [comment] 2020-06-12 13:03
Screenshots are attached.
I don't believe I changed anything, but today it's working. How bizarre!
I even plugged and unplugged other USB devices to see if that had made a difference, and it still works.
![screenshot 1591966858](https://user-images.githubusercontent.com/3490850/84505320-73cb9000-acb5-11ea-95de-3c6b6ae140f4.png)
![screenshot 1591965783](https://user-images.githubusercontent.com/3490850/84504957-c193c880-acb4-11ea-9d33-c5a9fbdb064a.png)
![screenshot 1591964801](https://user-images.githubusercontent.com/3490850/84504956-c193c880-acb4-11ea-8a86-603d3adc5be6.png)

I can't leave it on 'Auto' or else it's some half-working, half-broken layout (could this be the SNES profile?).
I shall keep an eye on changing anything if it happens again!

**Comment by Exequiel3k** [comment] 2020-07-25 00:26
I just want to report I have the same issues using mayflash adaptor with genuine n64 controllers. My only fix has been to use older builds

**Comment by loganmc10** [comment] 2020-10-25 00:28
I'm sorry I know this is a very old issue, I believe I have it fixed, it hasn't been released yet, but you can get it here:

https://ci.appveyor.com/api/buildjobs/dki8rmuj7jxu1tbo/artifacts/m64p-win64-f6da15d.zip

Mayflash adapters still won't work with the "Auto" profile, but you should be able to create a custom profile that will work.

@Exequiel3k @bast496 @Jaffacakelover please let me know if you can use your Mayflash adapters now

**Comment by loganmc10** [comment] 2020-10-25 15:10
This should be fixed in the latest release: https://github.com/loganmc10/m64p/releases/tag/Oct252020

Please re-open if it's still an issue

**Closed by loganmc10** 2020-10-25 15:10 UTC

**Comment by Exequiel3k** [comment] 2020-12-13 13:54
Hi,
I tried using the adaptor and it doesn’t detect button presses, when trying to configure a profile.
I selected the appropriate gamepad device for all four players and none worked
When trying to config...
