### ISSUE TITLE
GLideN64 Bilinear filtering no use

### ISSUE THREAD

**Issue by shinslash** [loganmc10/m64p#118] opened 2021-01-20 03:55 UTC
This issue also in the pj64 build from one day in 2020. But only a few people care.
https://github.com/gonetz/GLideN64/issues/2346
Use GLideN64 public release  4.0 you can see the difference.

**Comment by loganmc10** [comment] 2021-01-20 04:01
m64p just uses the upstream build of GLideN64, so this is a duplicate of the issue you've linked

**Closed** 2021-01-20 04:39 UTC
