### ISSUE TITLE
Custom configDirPath value still causes "Mupen64Plus" dir to be created

### ISSUE THREAD

**Issue by redactedscribe** [loganmc10/m64p#233] opened 2022-01-19 21:08 UTC
**Describe the bug**
I'm not sure if there is a purpose for the "%appdata%\Mupen64Plus" config dir other than the config files, but when configDirPath is set to a location other than the default (`$CONFIG_PATH$`), the "Mupen64Plus" directory is still being created, just empty.

**To Reproduce**
1. Set configDirPath to "$APP_PATH$/config" for example
2. Delete "%appdata%\Mupen64Plus"
3. Run m64p
4. Empty "%appdata%\Mupen64Plus" created on program launch

**Expected behavior**
Don't create unnecessary empty directory.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 11 Pro

**Comment by loganmc10** [comment] 2022-01-19 21:10
Other data is still stored in %appdata%\Mupen64Plus, for instance, screenshots and save files from games will end up there

**Comment by redactedscribe** [comment] 2022-01-19 21:42
That explains it.

In the future, I'd like to see m64p be even more portable. Defining where the "Mupen64Plus" directory is created via "mupen64plus-gui.ini" could work, then those looking for portability and those needing to ensure writeability would both be covered. This may nullify any reason to have specific control over where the config ini/cfg files are saved if _all_ the user data files can be saved to a custom location.

This would [allow Scoop to persist](https://github.com/ScoopInstaller/Scoop/wiki/Persistent-data) all data (not only the configs) as the "Mupen64Plus" dir could be set to be written to the program's directory.

**Comment by loganmc10** [comment] 2022-01-19 21:46
closig as a duplicate of https://github.com/loganmc10/m64p/issues/227

**Closed by loganmc10** 2022-01-19 21:46 UTC
Labels: wontfix
