### ISSUE TITLE
[Feature Request] Use the GlideN64 version that has all the features

### ISSUE THREAD

**Issue by Toadfield** [loganmc10/m64p#165] opened 2021-06-01 06:08 UTC
M64P's GlideN64 doesn't have all the features,texture enhancement options aren't available.
M64P is the most accurate out of the box standalone way to emulate the N64,so it would be really cool if this feature would be impemented.
I know I can just use standard Mupen64+,but that doesn't have parallel plugins and netplay support.
I don't see any disadvantage in that feature,cause it would make the experience better.

**Comment by loganmc10** [comment] 2021-06-01 15:58
Duplicate of https://github.com/loganmc10/m64p/issues/72 https://github.com/loganmc10/m64p/issues/51 https://github.com/loganmc10/m64p/issues/43 https://github.com/loganmc10/m64p/issues/26 https://github.com/loganmc10/m64p/issues/21 https://github.com/loganmc10/m64p/issues/18 and https://github.com/loganmc10/m64p/issues/13 :)

**Closed by loganmc10** 2021-06-01 15:58 UTC

**Comment by Toadfield** [comment] 2021-06-01 22:02
But in the duplicates you didn't answer why this feature isn't implemented.
So what is the exact reason why this isn't implemented?
I don't really see a disadvantage,it would just give the perfect out of box experience,for me texture packs and texture enhancement is nacessery and I don't want to use project64 with wine.

**Comment by loganmc10** [comment] 2021-06-01 22:06
It's just not a quality feature, it doesn't work well. You can go onto the GLideN64 issue tracker and find many issues relating to HD textures and texture enhancements. A lot of that has to do with the code in GLideN64, and a lot of it has to do with the poor quality/age of many of the packs.

It's the same reason there isn't cheat support, I had a really basic/bad implementation for cheats, but I wasn't proud of it, so I just removed it altogether. The emulator has enough bugs without including things that are poorly implemented.

**Comment by Toadfield** [comment] 2021-06-01 22:36
But some texture packs work good and I never had problems with texture enhancement on other N64 Emulators.
And you could just add an "Experimental" label to cheat codes and texture options,cause then I could use the features that work with those options and if something doesn't work I could just disable it,that would be better than don't use those options at all,cause for me many texture packs and texture enhancements worked and I really liked them.
For the cheat menu,which cheat plugin do you use?
Cause can't you just use the normal Project64 cheat plugin?
Or did that also not work?

**Comment by Toadfield** [comment] 2021-06-03 05:39
I mean what is the big advantage of removing features completely cause they sometimes not work instead of just adding an "experimental" label?

**Comment by Toadfield** [comment] 2021-06-06 13:08
I don't see any advantage by removing experimental features,many texture packs work good and this emulator would be perfect if it would just have all the GlideN64 features.

**Comment by loganmc10** [comment] 2021-06-06 13:15
The next build/release is going to replace GlideN64 with ParaLLEl-RDP, which doesn't support texture packs at all, so its a moot point.

**Comment by Toadfield** [comment] 2021-06-06 14:08
But even though GildeN64 is not as accurate as ParaLLEL,it has many fatures that ParaLLEL doesn't have.
So in my opinion it would be better if you could choose which you want to use in the settings instead of removing GildeN64 completely.

**Comment by Toadfield** [comment] 2021-06-06 14:14
The same for the cheats,it would be cool if you could just choose if you want to use it or not instead of removing it completely.
Btw why didn't the cheats work correctly? I mean cheats for Project64 work.

**Comment by Jj0YzL5nvJ** [comment] 2021-06-06 21:25
> Btw why didn't the cheats work correctly? I mean cheats for Project64 work.

loganmc10/m64p#156
They also work here if you know how to obfuscate them. Why bother to compete with PJ64 on its own turf?

**Comment by Toadfield** [comment] 2021-06-07 08:06
> They also work here if you know how to obfuscate them.

But it doesn't work out of the box
>Why bother to compete with PJ64 on its own turf?

Many things that PJ64 does are good,the only problem is that it isn't available for Linux natively.
