### ISSUE TITLE
Pokémon Stadium Clefairy minigame

### ISSUE THREAD

**Issue by jejethekiller** [loganmc10/m64p#36] opened 2020-05-14 17:40 UTC
The game shows hexadecimals and crashes when trying to leave the mini-game
![Image1](https://user-images.githubusercontent.com/65362191/81967086-681e7800-95e8-11ea-8bc8-c7e170757f04.png)

**Comment by loganmc10** [comment] 2020-05-17 13:49
Can you please provide a save state I could use to reproduce this issue?

**Comment by jejethekiller** [comment] 2020-05-18 03:17
Sure! Here it is. I replaced it to a ".txt" file because GitHub dont accept ".state" file.
[stadium.txt](https://github.com/loganmc10/m64p/files/4641816/stadium.txt)
 I dont know if it will work if you replace it to ".state" file again

**Comment by loganmc10** [comment] 2020-06-08 15:48
Thanks, I located the source of the issue and reported it to the upstream project (GLideN64) you can track the progress here:
https://github.com/gonetz/GLideN64/issues/2290

I'm going to close this issue, since the issue lies with GLideN64

**Closed by loganmc10** 2020-06-08 15:48 UTC
