### ISSUE TITLE
m64p crashes after clicking on advanced settings

### ISSUE THREAD

**Issue by Turaltay** [loganmc10/m64p#157] opened 2021-04-30 14:48 UTC
I downloaded the latest build of m64p and it crashes immediately after i click on advanced settings. Is this a known problem and fixable?

**Comment by loganmc10** [comment] 2021-04-30 19:49
Sorry I can't reproduce this, can you post some more details, like what OS you're using? Are you trying to do this while a game is running, or when the game is stopped?

**Comment by Turaltay** [comment] 2021-04-30 19:56
> 
> 
> Sorry I can't reproduce this, can you post some more details, like what OS you're using? Are you trying to do this while a game is running, or when the game is stopped?

I use a Windows 10 64-bit system. My GPU is a Nvidia Geforce GTX 970. I downloaded the file m64p-win64-a0367b2.zip, started it, clicked on advanced settings and it crashed. I will try it on a different PC too and check if there is the same problem.

**Comment by Turaltay** [comment] 2021-04-30 20:21
Tried it on my brothers PC too. He has a Windows 10 system too and a AMD Fury X. Same thing happens. If you click on advanced settings the emulator crashes. Doesn't matter if a game runs or not.

**Comment by Jj0YzL5nvJ** [comment] 2021-05-01 05:57
> I downloaded the latest build of m64p and it crashes immediately after i click on advanced settings. Is this a known problem and fixable?

> I downloaded the file m64p-win64-a0367b2.zip, started it, clicked on advanced settings and it crashed.

The crash is perfectly normal if you don't unzip.

**Comment by Turaltay** [comment] 2021-05-01 06:06
> 
> 
> > I downloaded the latest build of m64p and it crashes immediately after i click on advanced settings. Is this a known problem and fixable?
> 
> > I downloaded the file m64p-win64-a0367b2.zip, started it, clicked on advanced settings and it crashed.
> 
> The crash is perfectly normal if you don't unzip.

I unzipped the emulator before starting it. Sorry that i didn't mention that.

**Comment by Jj0YzL5nvJ** [comment] 2021-05-01 07:09
I tested on **Win10 Enterprise LTSC 2019** (version 1809) and **Win10 Professional** (version 2004). I can't reproduce with the unzipped files.

- Try closing the applications that are running in the background (tray icons) and that you have in common with the affected computers (chrome, spotify, afterburner, etc).
- Make sure you don't have any strange executable or library files in your user profile (*.exe, *.dll):
```
explorer "%LOCALAPPDATA%\VirtualStore"
explorer "%USERPROFILE%"
```

What's your "`Language for non-Unicode programs`" (aka ASCII)?

**Comment by Turaltay** [comment] 2021-05-01 08:10
> 
> 
> I tested on **Win10 Enterprise LTSC 2019** (version 1809) and **Win10 Professional** (version 2004). I can't reproduce with the unzipped files.
> 
>     * Try closing the applications that are running in the background (tray icons) and that you have in common with the affected computers (chrome, spotify, afterburner, etc).
> 
>     * Make sure you don't have any strange executable or library files in your user profile (*.exe, *.dll):
> 
> 
> ```
> explorer "%LOCALAPPDATA%\VirtualStore"
> explorer "%USERPROFILE%"
> ```
> 
> What's your "`Language for non-Unicode programs`" (aka ASCII)?

My language for non-Unicode programs is german because i am from germany. Could that be the problem?

**Comment by Jj0YzL5nvJ** [comment] 2021-05-01 10:19
> My language for non-Unicode programs is german because i am from germany. Could that be the problem?

In theory no, in practice maybe... Spanish is especially problematic, some programs only work correctly with the Spanish from Spain and fail with the Spanish from any other country. SolidWorks for instance.
[ePSXe doesn't display valid icons in Windows Explorer in French and Russian, but it does when switching to Spanish or English and vice versa, etc.](https://www.ngemu.com/threads/no-icon-in-exe.201929/)

Try to run `bcdedit /enum` as administrator. **If** `nx` has a value other than `OptIn`, restore it with `bcdedit /set nx OptIn` and reboot.

**Comment by Turaltay** [comment] 2021-05-01 10:32
> 
> 
> > My language for non-Unicode programs is german because i am from germany. Could that be the problem?
> 
> In theory no, in practice maybe... Spanish is especially problematic, some programs only work correctly with the Spanish from Spain and fail with the Spanish from any other country. SolidWorks for instance.
> [ePSXe doesn't display valid icons in Windows Explorer in French and Russian, but it does when switching to Spanish or English and vice versa, etc.](https://www.ngemu.com/threads/no-icon-in-exe.201929/)
> 
> Try to run `bcdedit /enum` as administrator. **If** `nx` has a value other than `OptIn`, restore it with `bcdedit /set nx OptIn` and reboot.

The value for nx is already OptIn. It seems like that i maybe found the problem. We have the letters Ö, Ä and Ü in our language. My username has a Ö as a letter inside it. My brother has a Ö too in his username and on his PC. I tried the advanced settings of m64p on a third PC without a username that has these letters. It worked. I know that some programs struggle with these letters. Question is if that is fixable.

**Comment by Jj0YzL5nvJ** [comment] 2021-05-01 21:59
<details>
  <summary>Now I can reproduce the crash</summary>

<img src="https://i.imgur.com/0ATpnl9.png" alt="" class="">

</details>

[test.zip](https://github.com/loganmc10/m64p/files/6410350/test.zip)

> Question is if that is fixable.

Yes.

**Comment by Turaltay** [comment] 2021-05-02 06:42
Would be happy if you could fix and implement this in future builds.

**Comment by Jj0YzL5nvJ** [comment] 2021-05-17 01:16
UI-Console shows a wrong configuration path but uses the correct one.
mupen64plus/mupen64plus-ui-console#71

**Comment by loganmc10** [comment] 2021-05-30 16:41
@Turaltay can you try the latest release? https://github.com/loganmc10/m64p/releases/tag/v2021.5.30

I tried to make some changes to support non-Latin characters in the path, although I didn't test it..

**Comment by Turaltay** [comment] 2021-05-30 18:34
@loganmc10 Thank you i tried it but it still crashes.

**Comment by loganmc10** [comment] 2021-05-30 18:39
Are you able to launch games that exist in the path with non Latin characters? Is it just the advanced settings that crashes?

**Comment by Turaltay** [comment] 2021-05-30 20:05
@loganmc10 Launching games from that path works without any problem. Only two things are not working. Advanced settings and the changing of anything in the controller settings. Seems like everything that includes reading works. Writing not.

**Comment by loganmc10** [comment] 2021-05-30 21:41
Ok, I'm not sure what else I could do to reproduce this. I do all my development on Linux, I tried putting the emulator in:

```
~/Documents/LogÖn/m64p
```
And set the config_dir to that path, but it didn't crash or anything, it seemed to work normally

**Comment by loganmc10** [comment] 2021-05-30 21:43
What I would recommend in your case, is to put the emulator somewhere outside the path with the non-Latin character (like C:\m64p or something)

And then in mupen64plus-gui.ini set:
```
configDirPath=some-path-that-has-only-latin-characters 
```
That should make it save mupen64plus.cfg to that path, then there shouldn't be any reading/writing inside your home directory.

**Comment by Turaltay** [comment] 2021-05-30 21:52
@loganmc10 Wow that actually worked! It is not crashing anymore and i can save my settings. Thank you for the hint! It is good that it works now for me but it would be nice if we could find a solution that works out of the box. I am pretty sure that not every m64plus user with the same problem will look here to use this workaround.

**Comment by loganmc10** [comment] 2021-05-30 22:28
Ok can you try one more build?
https://github.com/loganmc10/m64p/suites/2869204394/artifacts/64101547

You'll need to unzip it twice (it's a zip inside a zip, that's how GitHub Actions builds them), when you open it, it'll prompt you to update, just choose "no". Let me know if that works inside your home directory

**Comment by Turaltay** [comment] 2021-05-31 05:12
Same as before. It crashes. It works if i change configDirPath=$CONFIG_PATH$ to configDirPath=$APP_PATH$.

**Comment by loganmc10** [comment] 2021-05-31 17:18
I gave it one more try here: https://github.com/loganmc10/m64p/suites/2875625642/artifacts/64289182

That's probably as good as I can get it, if it's still having issues I assume there might be some work that needs to be done inside mupen64plus-core to get it working.

**Comment by Turaltay** [comment] 2021-05-31 17:28
Unfortunately it is still crashing. As already mentioned i had fixed it by setting $CONFIG_PATH$ to $APP_PATH$ for configDirPath. Is it important that there is $CONFIG_PATH$ set? Because the app path and config path are the same.

**Comment by loganmc10** [comment] 2021-05-31 18:02
CONFIG_PATH is where mupen64plus.cfg and the input settings are written, it can be anywhere, some people make it the same as APP_PATH to make the application portable.

**Comment by loganmc10** [comment] 2021-05-31 19:15
So I do think I have it working now: https://github.com/loganmc10/m64p/suites/2876226489/artifacts/64305285

I tested it on my computer inside a path with a non-Latin character. However, I did look through the code for mupen64plus-core, there are a lot of cases where it calls ```fopen``` to open files, which doesn't work on Windows for Unicode characters.

So you can give it a try, I don't think it will crash anymore, but it might have issues saving screenshots, save games, etc... I would still recommend putting things in a path with only Latin characters if possible.

**Comment by Turaltay** [comment] 2021-05-31 19:45
This fixed one of the problems. I am now able to save my controller profile. The emulator is still crashing while clicking on advanced settings. I moved it to a folder in D: without any special characters but it still crashed. I looked the data up and it seems like m64p saves some files in:

- C:\Users\my username with Ö\AppData\Local\Temp
- C:\Users\my username with Ö\AppData\Local\CrashDumps
- C:\Users\my username with Ö\AppData\Roaming\Mupen64Plus --> mupen64plus.cfg file is here

Something in this structure seems to make problems. There are some DMP-Files in the CrashDumps folder. I attached you one. Maybe you can analyse it?

[mupen64plus-gui.exe.6732.dmp.zip](https://github.com/loganmc10/m64p/files/6572007/mupen64plus-gui.exe.6732.dmp.zip)

**Comment by loganmc10** [comment] 2021-06-01 03:21
Ok I think I'm starting to understand this problem better, @Turaltay can you give this build a try?

https://github.com/loganmc10/m64p/suites/2878187738/artifacts/64359083

If it works, I wouldn't mind if you tried the following:
* Saving/loading a save state
* Taking a screenshot

All of that stuff should appear in ```C:\Users\my username with Ö\AppData\Roaming\Mupen64Plus```

**Comment by Turaltay** [comment] 2021-06-01 06:21
Wow you fixed it! It is not crashing anymore if i click on advanced settings. Taking a screenshot works too. Only thing that doesn't work is saving and loading a save state. Clicking on Save State to... or Load State From leads to the same result.

**Comment by loganmc10** [comment] 2021-06-01 11:39
What happens when you try to save or load a save state. Does it crash, or just do nothing?

**Comment by Turaltay** [comment] 2021-06-01 12:29
Nothing happens. The emulator and the game are still working but it doesn't save or load anything.

**Comment by loganmc10** [comment] 2021-06-01 14:09
Ok I believe I have save states fixed: https://github.com/loganmc10/m64p/suites/2882605683/artifacts/64491409

Let me know if you see any other issues, if it looks good, I've got a patch I can submit to mupen64plus-core

**Comment by loganmc10** [comment] 2021-06-10 15:51
Fixed in https://github.com/loganmc10/m64p/releases/tag/v2021.6.10

**Closed by loganmc10** 2021-06-10 15:51 UTC
Labels: PR submitted upstream
