### ISSUE TITLE
Cant use and find Texture enhancement after 1st April Release

### ISSUE THREAD

**Issue by amorosog** [loganmc10/m64p#51] opened 2020-07-09 20:25 UTC
After 1st April Release the Texture enhancement option is no more available, even setting txHiresEnable=1 on ini the custom textures is not working anymore.

**Comment by loganmc10** [comment] 2020-07-09 20:33
Duplicate of https://github.com/loganmc10/m64p/issues/43

**Closed by loganmc10** 2020-07-09 20:33 UTC
