### ISSUE TITLE
Taking a screenshot crashes emulator when LLE Graphics is enabled in SM64

### ISSUE THREAD

**Issue by zant0** [loganmc10/m64p#111] opened 2021-01-03 13:23 UTC
build: Dec 15, 2020
OS: Windows 10
Game: Super Mario 64 NTSC-U
LLE Graphics: enabled
VI Filter: disabled

If you press F12 to take a screenshot or go over the menu the emulator closes itself and generates a 0 byte big broken png file in the screenshot folder. If VI Filter is enabled taking a screenshot works. I also tested this with Mario Kart 64 but there it works with LLE Graphics enabled and VI Filter disabled.

**Comment by Jj0YzL5nvJ** [comment] 2021-01-03 17:11
ata4/angrylion-rdp-plus#89

**Comment by loganmc10** [comment] 2021-01-03 17:20
Yeah I'm going to close this, @Jj0YzL5nvJ linked to the related issue. The issue is with angrylion, not specific to m64p

**Closed by loganmc10** 2021-01-03 17:20 UTC

**Comment by Jj0YzL5nvJ** [comment] 2021-01-03 18:31
I think it's most likely related to a problem with mupen64plus-core... gonetz/GLideN64#119
