### ISSUE TITLE
Manjaro KDE cannot open the Video or Input Plugin Panel

### ISSUE THREAD

**Issue by CrankySupertoon** [loganmc10/m64p#11] opened 2020-03-29 17:13 UTC

**Comment by loganmc10** [comment] 2020-03-30 03:32
This is typically because you are missing some required shared libraries, can you do an "ldd mupen64plus-video-GLideN64.so" and post the output?

**Comment by CrankySupertoon** [comment] 2020-03-30 14:56
Yeah give me like an hour

**Comment by loganmc10** [comment] 2020-03-30 16:18
Also, did you compile this from source, or download the binary from https://github.com/loganmc10/m64p/releases ?

**Comment by CrankySupertoon** [comment] 2020-03-30 16:31
I got the binary since the app is closed source? It’s $1 on Patreon right?

**Comment by loganmc10** [comment] 2020-03-30 16:34
No the Patreon is closed, everything is available on https://github.com/loganmc10/m64p/releases now

**Comment by CrankySupertoon** [comment] 2020-03-30 18:57
Ahh, Currently i was an old Patreon Binary build. The New Binary does the same issue.

the stacktrace from the command you told me to run is here

[parkerhanegan@parker-pc m64p]$ ldd mupen64plus-video-GLideN64.so
        linux-vdso.so.1 (0x00007ffc39b46000)
        libQt5Widgets.so.5 => /usr/lib/libQt5Widgets.so.5 (0x00007fcbd464a000)
        libQt5Gui.so.5 => /usr/lib/libQt5Gui.so.5 (0x00007fcbd3fa1000)
        libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007fcbd3f69000)
        libz.so.1 => /usr/lib/libz.so.1 (0x00007fcbd3f4f000)
        libQt5Core.so.5 => /usr/lib/libQt5Core.so.5 (0x00007fcbd3a16000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007fcbd382d000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007fcbd36e5000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007fcbd351f000)
        libGL.so.1 => /usr/lib/libGL.so.1 (0x00007fcbd3499000)
        libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007fcbd33cb000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fcbd33a9000)
        libmd4c.so.0 => /usr/lib/libmd4c.so.0 (0x00007fcbd3393000)
        libharfbuzz.so.0 => /usr/lib/libharfbuzz.so.0 (0x00007fcbd328d000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fcbd3273000)
        libsystemd.so.0 => /usr/lib/libsystemd.so.0 (0x00007fcbd31cc000)
        libdouble-conversion.so.3 => /usr/lib/libdouble-conversion.so.3 (0x00007fcbd31b5000)
        libicui18n.so.65 => /usr/lib/libicui18n.so.65 (0x00007fcbd2ec2000)
        libicuuc.so.65 => /usr/lib/libicuuc.so.65 (0x00007fcbd2ce0000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007fcbd2cd9000)
        libpcre2-16.so.0 => /usr/lib/libpcre2-16.so.0 (0x00007fcbd2c55000)
        libzstd.so.1 => /usr/lib/libzstd.so.1 (0x00007fcbd2bab000)
        libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x00007fcbd2a83000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007fcbd55a5000)
        libGLdispatch.so.0 => /usr/lib/libGLdispatch.so.0 (0x00007fcbd29cc000)
        libGLX.so.0 => /usr/lib/libGLX.so.0 (0x00007fcbd2999000)
        libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007fcbd2984000)
        libgraphite2.so.3 => /usr/lib/libgraphite2.so.3 (0x00007fcbd295f000)
        librt.so.1 => /usr/lib/librt.so.1 (0x00007fcbd2954000)
        liblzma.so.5 => /usr/lib/liblzma.so.5 (0x00007fcbd292c000)
        liblz4.so.1 => /usr/lib/liblz4.so.1 (0x00007fcbd290a000)
        libgcrypt.so.20 => /usr/lib/libgcrypt.so.20 (0x00007fcbd27ec000)
        libicudata.so.65 => /usr/lib/libicudata.so.65 (0x00007fcbd0d39000)
        libpcre.so.1 => /usr/lib/libpcre.so.1 (0x00007fcbd0cc7000)
        libX11.so.6 => /usr/lib/libX11.so.6 (0x00007fcbd0b87000)
        libgpg-error.so.0 => /usr/lib/libgpg-error.so.0 (0x00007fcbd0b65000)
        libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007fcbd0b3b000)
        libXau.so.6 => /usr/lib/libXau.so.6 (0x00007fcbd0b34000)
        libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007fcbd0b2c000)

compiling from source as we speak

**Comment by CrankySupertoon** [comment] 2020-03-30 19:10
This is the error btw 
```malloc_consolidate(): invalid chunk size
Segmentation fault (core dumped)```

**Comment by CrankySupertoon** [comment] 2020-03-30 19:10
This is the error btw 

malloc_consolidate(): invalid chunk size
Segmentation fault (core dumped)

**Comment by loganmc10** [comment] 2020-03-30 19:57
I'm not sure how much help I can be, I downloaded Manjaro and loaded in on a VM, I was able to launch it without issues.

Do games work, just not the config dialoags?

**Comment by CrankySupertoon** [comment] 2020-03-30 21:47
I can’t access the config menus. I could access the input before you made the QT one

**Comment by CrankySupertoon** [comment] 2020-04-07 20:08
any other info?

**Comment by loganmc10** [comment] 2020-04-07 20:08
No sorry I don't think I can help you on this one

**Comment by dbermond** [comment] 2020-04-10 21:59
Maybe the OP is referring to the plain [mupen64plus-gui](https://github.com/m64p/mupen64plus-gui/) compiled from source and not [m64p](https://github.com/loganmc10/m64p/), since there is no issue tracker at mupen64plus-gui sources on GitHub.

If this is the case, the window for Video Settings also does not work for me with a vanilla [GLideN64](https://github.com/gonetz/GLideN64/), but it requires a specially patched version from https://github.com/loganmc10/GLideN64/tree/NUI. For showing the Controller Settings window I needed the [mupen64plus-input-qt](https://github.com/m64p/mupen64plus-input-qt/) plugin to be installed. And at the time of writing it also needs a special [mupen64plus-core](https://github.com/loganmc10/mupen64plus-core/) from https://github.com/loganmc10/mupen64plus-core/tree/m64p to build. Please correct me if I'm wrong ;)

I understand that this is made by design, but it would be good to see the plain mupen64plus-gui to be able to work without these special dependencies, acting as a regular standalone GUI :)

**Comment by loganmc10** [comment] 2020-04-10 22:07
Yes you are correct, it's not really designed to work independently, it's all designed to work as a cohesive package.

The development of mupen64plus-core can be very slow because of inactivity of the people able to merge PRs, so you are correct that I have forked mupen64plus-core, and there are currently some API changes that would make mupen64plus-gui incompatible with the upstream mupen64plus-core (currently, hopefully that problem goes away when the pending PRs are merged into master)

I don't have any plans to make mupen64plus-gui "backend agnostic", it is designed to work together with the "m64p" package.

**Comment by dbermond** [comment] 2020-04-11 00:02
@loganmc10 Thank you for the explanation.

I hope those PR can be merged soon, so mupen64plus-gui can work with upstream mupen64plus-core. Actually it mostly works fine with upstream for me. :)

**Closed** 2020-04-11 13:57 UTC

**Comment by CrankySupertoon** [comment] 2020-04-22 16:19
No i am refering to M64P. I have got the binary from releases, the AUR Package, and just tried to compile it all failed.

**Comment by CrankySupertoon** [comment] 2020-04-22 16:20
```ldd mupen64plus-video-GLideN64.so    
        linux-vdso.so.1 (0x00007ffc5cfbf000)
        /usr/${LIB}/libgtk3-nocsd.so.0 => /usr/lib/libgtk3-nocsd.so.0 (0x00007f537cb0b000)
        libGL.so.1 => /usr/lib/libGL.so.1 (0x00007f537ca30000)
        libGLU.so.1 => /usr/lib/libGLU.so.1 (0x00007f537c9bf000)
        libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007f537c8f1000)
        libQt5Widgets.so.5 => /usr/lib/libQt5Widgets.so.5 (0x00007f537c251000)
        libQt5Gui.so.5 => /usr/lib/libQt5Gui.so.5 (0x00007f537bba5000)
        libQt5Core.so.5 => /usr/lib/libQt5Core.so.5 (0x00007f537b66a000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f537b481000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f537b33b000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f537b175000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f537b170000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f537b14e000)
        libGLdispatch.so.0 => /usr/lib/libGLdispatch.so.0 (0x00007f537b095000)
        libGLX.so.0 => /usr/lib/libGLX.so.0 (0x00007f537b062000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f537b048000)
        libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007f537b035000)
        libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007f537affd000)
        libz.so.1 => /usr/lib/libz.so.1 (0x00007f537afe3000)
        libharfbuzz.so.0 => /usr/lib/libharfbuzz.so.0 (0x00007f537aedd000)
        libmd4c.so.0 => /usr/lib/libmd4c.so.0 (0x00007f537aec7000)
        libsystemd.so.0 => /usr/lib/libsystemd.so.0 (0x00007f537ae20000)
        libdouble-conversion.so.3 => /usr/lib/libdouble-conversion.so.3 (0x00007f537ae09000)
        libicui18n.so.65 => /usr/lib/libicui18n.so.65 (0x00007f537ab16000)
        libicuuc.so.65 => /usr/lib/libicuuc.so.65 (0x00007f537a934000)
        libpcre2-16.so.0 => /usr/lib/libpcre2-16.so.0 (0x00007f537a8ae000)
        libzstd.so.1 => /usr/lib/libzstd.so.1 (0x00007f537a804000)
        libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x00007f537a6dc000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007f537d105000)
        libX11.so.6 => /usr/lib/libX11.so.6 (0x00007f537a59c000)
        libgraphite2.so.3 => /usr/lib/libgraphite2.so.3 (0x00007f537a577000)
        librt.so.1 => /usr/lib/librt.so.1 (0x00007f537a56a000)
        liblzma.so.5 => /usr/lib/liblzma.so.5 (0x00007f537a542000)
        liblz4.so.1 => /usr/lib/liblz4.so.1 (0x00007f537a520000)
        libgcrypt.so.20 => /usr/lib/libgcrypt.so.20 (0x00007f537a402000)
        libicudata.so.65 => /usr/lib/libicudata.so.65 (0x00007f5378951000)
        libpcre.so.1 => /usr/lib/libpcre.so.1 (0x00007f53788df000)
        libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007f53788b3000)
        libgpg-error.so.0 => /usr/lib/libgpg-error.so.0 (0x00007f5378891000)
        libXau.so.6 => /usr/lib/libXau.so.6 (0x00007f537888c000)
        libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007f5378884000)
```

**Comment by Mario0051** [comment] 2020-05-02 00:06
Set the paths to the correct directories. Settings > Plugin and Path Selection
