### ISSUE TITLE
Auto updater not working

### ISSUE THREAD

**Issue by GoodWall533** [loganmc10/m64p#83] opened 2020-10-30 13:00 UTC
Hi, I recently installed m64p and I tried using the auto updater but there is a slight problem. When I open the emulator, it asks me if I want to update, I click yes to update and then it says 'downloading updater' but then it just closes the emulator and doesn't update anything. When I open the emulator again it still asks me if I want to update it. Any idea on what's causing this?

**Comment by loganmc10** [comment] 2020-10-30 13:24
Can you give me some details about your environment? OS, where you've installed m64p, anything else that comes to mind

**Comment by GoodWall533** [comment] 2020-10-30 14:30
I use windows 10 and if by 'installed' I mean downloaded the zip from the github and extracted it on a folder that's on my desktop.

**Comment by loganmc10** [comment] 2020-10-30 15:42
I wonder if it's related to this issue: https://github.com/loganmc10/m64p/issues/84

It's possible your antivirus is blocking the program because it is downloading and copying files from the internet (and it's an unknown program).

I'll need to think on this one

**Comment by loganmc10** [comment] 2020-10-30 15:47
@GoodWall533 what antivirus do you have on your computer?

**Comment by GoodWall533** [comment] 2020-10-30 15:48
standard for W10. Windows Defender.

**Comment by loganmc10** [comment] 2020-10-30 15:52
Ok, it may be the same issue, did you see any feedback from Windows Defender?

I'll work on getting it OKed by Windows Defender

**Comment by GoodWall533** [comment] 2020-10-30 15:57
No. no feedback at all. sorry.

**Comment by loganmc10** [comment] 2020-11-01 13:19
Going to close this one as it's a duplicate of #84

**Closed by loganmc10** 2020-11-01 13:19 UTC
