### ISSUE TITLE
Rom Crashes on Launch

### ISSUE THREAD

**Issue by joeconner121** [loganmc10/m64p#221] opened 2021-10-31 00:53 UTC
Describe the bug
Same as #214 

To Reproduce

Open Emulator
Load Rom
Immediate Crash

Expected behavior
Game Loads Up

Screenshots

Desktop (please complete the following information):

    OS: Windows
    Version: 11
    GPU: AMD Ryzen 7 5800H with Radeon Graphics / NVIDIA GeForce RTX 3050 Ti Laptop GPU

Additional context
Appears to be identical issue to #214

**Comment by loganmc10** [comment] 2021-10-31 00:54
Duplicate of #214

**Closed by loganmc10** 2021-10-31 00:54 UTC
