### ISSUE TITLE
Image twitching/unstable image

### ISSUE THREAD

**Issue by thekovic** [loganmc10/m64p#176] opened 2021-06-09 15:52 UTC
**Describe the bug**
The edges of the rendered game image and some other select elements (usually text) are constantly twitching up and down by a couple of pixels. It's very noticeable and not very pleasant.

**Expected behavior**
Stable image without twitching.

**Screenshots**
Hard to convey through screenshots so I compiled a short video: https://www.youtube.com/watch?v=Cbw984HTtWI

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10
 - CPU: Intel Core i5 8300H
 - GPU: Nvidia Geforce GTX 1050Ti

**Additional context**
Observed in StarCraft 64 and Indiana Jones and the Infernal Machine. Latest build of M64P (with ParaLLEl-RDP). Default video settings (such as upscaling set to 1). Played with the M64P window maximized.

**Comment by loganmc10** [comment] 2021-06-09 16:02
I'll look into this a bit to see if there is anything that could be improved in the emulator core. This is an issue with interlacing, I believe you can probably fix it by doing:

![image](https://user-images.githubusercontent.com/848146/121389434-a54b5b80-c909-11eb-811a-9d18027be018.png)

**Comment by thekovic** [comment] 2021-06-09 16:07
That seems to have done the trick, thank you. Is the option off by default because it's considered less accurate?

**Comment by loganmc10** [comment] 2021-06-09 16:12
I believe Weave mode (which is what is enabled with the checkbox) doesn't do well at upscaling resolutions, you can see it in the Indiana Jones menu when the text is moving left.

Angrylion-Plus struggled with some of these shaking type issues as well, I'm not sure if that was all sorted out or not, I think it's a bit of a tricky issue to solve

**Comment by loganmc10** [comment] 2021-06-09 16:13
It's actually listed as a known issue on the libretro post about ParaLLEl-RDP:
![image](https://user-images.githubusercontent.com/848146/121391196-57375780-c90b-11eb-8e9b-8ed9faa48a3a.png)
https://www.libretro.com/index.php/parallel-n64-low-level-rdp-upscaling-is-finally-here/

**Comment by loganmc10** [comment] 2021-06-09 20:14
@thekovic I've played around with this a bit. I tested it in RetroArch and the shaking is present there as well, although it looks a bit different. Can you verify that? Do you have RetroArch installed?

I tested Weave mode at higher upscaling resolutions and I don't know if it's a better option. It seems to introduce quite a bit of what I would call "motion blur". I did file an issue with the upstream repo: https://github.com/Themaister/parallel-rdp/issues/24 although I don't know if I'll get any kind of response

**Comment by thekovic** [comment] 2021-06-09 20:21
@loganmc10 I don't have RetroArch installed, never used it before; but I'm willing to test

**Comment by loganmc10** [comment] 2021-06-09 20:23
There's probably no need, I just tested it on Linux as well as Windows, it's the same there.

I also tested the last build of m64p that included Angrylion, and the issue isn't present there. So I think it's pretty safe to assume the issue is with ParaLLEl-RDP. Given that it has its own repo, I'm going to close this, I'd suggest you follow: https://github.com/Themaister/parallel-rdp/issues/24 . You can subscribe to that issue to get notified if anything happens there.

**Closed by loganmc10** 2021-06-09 20:23 UTC

**Comment by loganmc10** [comment] 2021-06-10 15:52
I put out a fix for this in: https://github.com/loganmc10/m64p/releases/tag/v2021.6.10 can you try it and let me know how it looks to you?

The option between bob/weave has been removed. Now it's set to Weave all the time, but it does bob deinterlacing on the OpenGL side. It should reduce the weave artifacts while also removing the shaking

**Comment by thekovic** [comment] 2021-06-10 16:32
It got rid of the shaking but I'm seeing lots of what I presume are deinterlacing artifacts during movement. In terms of image quality, I think I preferred the previous Weave-only solution.

**Comment by loganmc10** [comment] 2021-06-10 16:42
Fair enough, I think what I'll do:
* Replace the upstream "Bob" mode with this one, I'll probably make this the default
* Put back the original Weave mode as it was

I'll do that for the next release

**Comment by thekovic** [comment] 2021-06-10 16:45
Aye, I can get behind that solution.
