### ISSUE TITLE
[bug / suggestion] Issues with making a portable version of m64p

### ISSUE THREAD

**Issue by RichardPaulAstley** [loganmc10/m64p#162] opened 2021-05-26 19:10 UTC
Hi ! 

These days, i've started to setup a portable emulators configuration in order to be able to play with my games and my saves with different PCs. I struggled a lot to find the right N64 emulator before discovering m64p.

I've started to configure all the paths and everything to make it portable, but I still can't make it. When I launch it from the flash drive, I get the error of "Failed to find core library". Also in a little note, I still have the "shaders" folder still being present in AppFolders, no way to edit that.

I'm not sure if i'm doing it wrong, or it's a bug, but could it be possible to make m64p portable ? If it's the case, what how could it be possible to setup that ? 

Thanks a lot.

**Comment by Jj0YzL5nvJ** [comment] 2021-05-27 00:41
> how could it be possible to setup that ?

[m64p_portable.zip](https://github.com/loganmc10/m64p/files/6550345/m64p_portable.zip)

**Comment by mogarithm** [comment] 2021-05-30 13:37
It's a very good workaround. But this portability should be the out-of-the-box default behaviour of m64p.

**Comment by loganmc10** [comment] 2021-05-30 13:45
Duplicate of https://github.com/loganmc10/m64p/issues/150

**Closed by loganmc10** 2021-05-30 13:45 UTC
Labels: help wanted
